name: flutter_nic_decoder
description: "Decodes user information from Sri Lankan NIC number."
publish_to: 'none'
version: 0.1.5+3
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_linkify: ^6.0.0
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.3
  flutter_svg: ^2.0.17
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
     - assets/social/github.svg
     - assets/social/discord.svg
     - assets/social/devdotto.svg

# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
