name: Flutter Build and Release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
  discussions: write
jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.27.0
      - name: Install dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --release
      - name: Rename APK with version
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/nic-app-${{ github.ref_name }}.apk
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/nic-app-${{ github.ref_name }}.apk
  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release-apk
          path: release-assets/
      - name: Generate Release Notes
        run: |
          PREV_TAG=$(git tag --sort=-v:refname | sed -n 2p)
          CURR_TAG=${{ github.ref_name }}
          RELEASE_NOTES="release-assets/release-notes.md"

          echo "# What's new?" > $RELEASE_NOTES

          if [ -z "$PREV_TAG" ]; then
            COMMITS=$(git log --pretty=format:"%s")
          else
            COMMITS=$(git log --pretty=format:"%s" $PREV_TAG..$CURR_TAG)
          fi

          FEATURES=$(echo "$COMMITS" | grep -iE "^feat: " | sed 's/^feat: //')
          FIXES=$(echo "$COMMITS" | grep -iE "^fix: " | sed 's/^fix: //')

          if [ -n "$FEATURES" ]; then
            echo -e "\n## Features" >> $RELEASE_NOTES
            echo "$FEATURES" | while read -r line; do echo "- $line"; done >> $RELEASE_NOTES
          fi

          if [ -n "$FIXES" ]; then
            echo -e "\n## Fixes" >> $RELEASE_NOTES
            echo "$FIXES" | while read -r line; do echo "- $line"; done >> $RELEASE_NOTES
          fi
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: release-assets/release-notes.md
          files: release-assets/nic-app-${{ github.ref_name }}.apk
