name: Releases
on:
  workflow_run:
    workflows: ["Builds"]
    types:
      - completed
      - success
permissions:
  contents: write
  discussions: write
jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release-apk
          path: release-assets/
      - name: Generate Release Notes
        run: |
          # Get previous tag
          PREV_TAG=$(git tag --sort=-v:refname | sed -n 2p)
          CURR_TAG=${{ github.ref_name }}
          RELEASE_NOTES="release-assets/release-notes.md"

          echo "# What's new?" > $RELEASE_NOTES

          # Get commits between tags
          if [ -z "$PREV_TAG" ]; then
            COMMITS=$(git log --pretty=format:"%s")
          else
            COMMITS=$(git log --pretty=format:"%s" $PREV_TAG..$CURR_TAG)
          fi

          FEATURES=$(echo "$COMMITS" | grep -iE "^feat: " | sed 's/^feat: //')
          FIXES=$(echo "$COMMITS" | grep -iE "^fix: " | sed 's/^fix: //')

          # Add features and fixes to release notes
          if [ -n "$FEATURES" ]; then
            echo -e "\n## Features" >> $RELEASE_NOTES
            echo "$FEATURES" | while read -r line; do echo "- $line"; done >> $RELEASE_NOTES
          fi

          if [ -n "$FIXES" ]; then
            echo -e "\n## Fixes" >> $RELEASE_NOTES
            echo "$FIXES" | while read -r line; do echo "- $line"; done >> $RELEASE_NOTES
          fi
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body_path: release-assets/release-notes.md
          files: release-assets/nic-app-${{ github.ref_name }}.apk
      - name: Update Changelog.md
        run: |
          CHANGELOG_FILE="Changelog.md"
          RELEASE_NOTES="release-assets/release-notes.md"
          TEMP_FILE="Changelog_temp.md"

          # Create Changelog.md if it doesn't exist
          if [ ! -f "$CHANGELOG_FILE" ]; then
            touch "$CHANGELOG_FILE"
          fi

          # Prepend new release notes
          {
            echo "## ${{ github.ref_name }}"
            cat "$RELEASE_NOTES"
            echo ""
            cat "$CHANGELOG_FILE"
          } > "$TEMP_FILE"

          mv "$TEMP_FILE" "$CHANGELOG_FILE"
      - name: Commit and push updated Changelog.md
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Changelog.md
          git commit -m "Update Changelog for ${{ github.ref_name }}"
          git push origin main
